apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    tier: vote
  name: vote
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vote
      tier: vote
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vote
        tier: vote
    spec:
      containers:
      - image: schoolofdevops/vote:v4
        name: vote
        resources: {}
