apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
  namespace: instavote
spec: 
  replicas: 5
  spec: 
    containers: 
    - image: schoolofdevops/vote:v4
      name: vote